services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - kafka-net
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_PROCESS_ROLES=broker
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_BROKER_ID=1
      - KAFKA_ENABLE_KRAFT=no   # 🚨 This disables KRaft mode
    depends_on:
      - zookeeper
    networks:
      - kafka-net


networks:
  kafka-net:
    driver: bridge


# docker run -d --name zookeeper \
#   --network kafka-net \
#   -e ALLOW_ANONYMOUS_LOGIN=yes \
#   bitnami/zookeeper:latest


# docker run -d --name kafka \
#   -p 9092:9092 \
#   -e KAFKA_NODE_ID=1 \
#   -e KAFKA_PROCESS_ROLES=broker,controller \
#   -e KAFKA_CONTROLLER_QUORUM_VOTERS=1@localhost:9093 \
#   -e KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT \
#   -e KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093 \
#   -e KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092 \
#   -e KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER \
#   -e KAFKA_LOG_DIRS=/tmp/kraft-combined-logs \
#   apache/kafka:latest
